### ISSUE TITLE
[Website Issue] Not all tags get generated for some reason 🤔

### ISSUE THREAD

**Issue by Wonkers0** [Wonkers0/DFSpigot#6]
![image](https://user-images.githubusercontent.com/106038003/180325949-2783dfd9-5307-4a5f-82e3-f941a43bdfce.png)
![image](https://user-images.githubusercontent.com/106038003/180325994-71f3261d-fde3-418d-ad69-6486a0af688a.png)

**Comment by Wonkers0** [comment]
Looking into it...

**Comment by Wonkers0** [comment]
Tried to be a smartass by crowding things into a singular loop 😔
Rolling to main site now

**Comment by UserUNP** [comment]
Les go wonk zero's killing it 😁😁👍👍😏

**Comment by CheaterTim** [comment]
:nerd_face:
